import {api,session,safeOrigin} from "@/lib/supabase";
import {amount,accounts,services} from "@/lib/accounting";
export const dynamic="force-dynamic";

const fail=(s:string,status=400)=>Response.json({error:s},{status});
export async function GET(){try{const {token}=await session();let all:any[]=[];let offset=0;while(true){const batch=await api(`/rest/v1/records?select=*&order=created.desc&limit=1000&offset=${offset}`,token);all.push(...batch);if(batch.length<1000)break;offset+=1000;}return Response.json(all,{headers:{"Cache-Control":"no-store"}})}catch(e:any){return fail(e.message==="SESSION_REQUIRED"?"انتهت الجلسة، سجل الدخول مجددًا":e.message==="FORBIDDEN"?"الحساب غير مصرح له بالدخول":"تعذر تحميل البيانات",e.message==="SESSION_REQUIRED"?401:e.message==="FORBIDDEN"?403:503)}}
export async function POST(req:Request){try{const {token,role}=await session();if(!["admin","accountant"].includes(role))return fail("حسابك للعرض فقط",403);const origin=req.headers.get("origin");if(origin&&new URL(req.url).origin!==origin)return fail("طلب غير مسموح",403);const b:any=await req.json();const kind=b.kind;const allowed=["client","supplier","contract","sale","purchase","receipt","payment","expense","entry","settings","item","movement"];if(!allowed.includes(kind))throw Error("نوع العملية غير صحيح");const d=b.data||{};const text=(v:any)=>String(v||"").trim().slice(0,500);d.name=text(d.name);d.notes=text(d.notes);d.phone=text(d.phone);d.address=text(d.address);d.vat=text(d.vat);if(d.vat&&!/^\d{15}$/.test(d.vat))throw Error("الرقم الضريبي يجب أن يتكون من 15 رقمًا");if(!/^\d{4}-\d{2}-\d{2}$/.test(b.date))throw Error("أدخل التاريخ");if(["client","supplier","contract"].includes(kind)&&!d.name)throw Error("الاسم مطلوب");if(["sale","purchase","contract"].includes(kind)){if(!services.includes(d.service))throw Error("حدد الخدمة");d.net=amount(d.net);if(d.net<=0)throw Error("المبلغ يجب أن يكون أكبر من صفر");const rate=Number(d.rate||0);if(![0,15].includes(rate))throw Error("نسبة الضريبة غير صحيحة");d.tax=Math.round(d.net*rate/100);d.total=d.net+d.tax;if(kind!=="contract"){const party=(await api(`/rest/v1/records?id=eq.${encodeURIComponent(d.party)}&select=kind&limit=1`,token))[0];if(party?.kind!==(kind==="sale"?"client":"supplier"))throw Error("اختر العميل أو المورد الصحيح")}}
if(["receipt","payment","expense"].includes(kind)){d.amount=amount(d.amount);if(d.amount<=0)throw Error("المبلغ يجب أن يكون أكبر من صفر");if(!["1010","1020"].includes(d.account))throw Error("اختر الصندوق أو البنك");if(kind!=="expense"){const invoice=(await api(`/rest/v1/records?id=eq.${encodeURIComponent(d.invoice)}&select=*&limit=1`,token))[0];if(invoice?.kind!==(kind==="receipt"?"sale":"purchase"))throw Error("اختر الفاتورة الصحيحة");d.party=invoice.data.party;}}
if(kind==="entry"){if(!Array.isArray(d.lines)||d.lines.length<2||d.lines.length>30)throw Error("أدخل سطرين على الأقل");d.lines=d.lines.map((l:any)=>{if(!accounts[l.account])throw Error("حساب غير صحيح");const debit=amount(l.debit),credit=amount(l.credit);if((debit>0)===(credit>0))throw Error("كل سطر يحتوي مبلغًا مدينًا أو دائنًا فقط");return {account:l.account,debit,credit}});const debit=d.lines.reduce((s:number,l:any)=>s+l.debit,0),credit=d.lines.reduce((s:number,l:any)=>s+l.credit,0);if(debit!==credit)throw Error("القيد غير متوازن: مجموع المدين يجب أن يساوي الدائن")}
if(kind==="item"){if(!d.name)throw Error("اسم الصنف مطلوب");d.unit=text(d.unit)||"وحدة";}
if(kind==="movement"){const item=(await api(`/rest/v1/records?id=eq.${encodeURIComponent(d.item)}&select=kind&limit=1`,token))[0];if(item?.kind!=="item")throw Error("اختر الصنف");d.quantity=Number(d.quantity);if(!Number.isFinite(d.quantity)||d.quantity<=0||d.quantity>1e6)throw Error("كمية غير صحيحة");if(!["in","out"].includes(d.direction))throw Error("حدد الحركة");}
const id=crypto.randomUUID();const prefixes:any={sale:"SAL",purchase:"PUR",receipt:"REC",payment:"PAY",expense:"EXP",entry:"JRN",client:"CUS",supplier:"SUP",contract:"CON",settings:"SET",item:"ITM",movement:"MOV"};const number=prefixes[kind]+"-"+Date.now().toString(36).toUpperCase()+"-"+id.slice(0,4);await api("/rest/v1/records",token,{method:"POST",body:JSON.stringify({id,kind,number,date:b.date,data:d,created:Date.now()})});return Response.json({id,number}, {status:201});}catch(e:any){const message=String(e.message);return fail(message==="SESSION_REQUIRED"?"انتهت الجلسة، سجل الدخول مجددًا":message==="FORBIDDEN"?"الحساب غير مصرح له":message.includes("insufficient_stock")?"الكمية المطلوبة تتجاوز المخزون المتاح":message.includes("overpayment")?"المبلغ يتجاوز المتبقي من الفاتورة":message.includes("D1")?"تعذر حفظ العملية. أعد المحاولة.":message,message==="SESSION_REQUIRED"?401:message==="FORBIDDEN"?403:400)}}
